import type { Metadata } from "next";
import { PT_Serif, Bree_Serif, } from "next/font/google";
import "./globals.css";

const ptSerif = PT_Serif({
  variable: "--font-ptSerif",
  weight: ["400", "700"],
  subsets: ["latin"],
});

const breeSerif = Bree_Serif({
  variable: "--font-breeSerif",
  weight: "400",
  subsets: ["latin"],
});

// need to change
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${breeSerif.variable} ${ptSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
